rootProject.name = 'neutron'

include 'neutron'
include 'neutron:api'
include 'neutron:api:cldcapi10'
include 'neutron:api:cldcapi11'
include 'neutron:api:midpapi20'
include 'neutron:neutron-android'
include 'neutron:neutron-cldc'
include 'neutron:neutron-examples'
include 'neutron:neutron-examples:neutron-demo'
include 'neutron:neutron-examples:neutron-fcview'
include 'neutron:neutron-extensions'
include 'neutron:neutron-extensions:neutron-device-large'
include 'neutron:neutron-extensions:neutron-device-minimum'
include 'neutron:neutron-extensions:neutron-device-resizable'
include 'neutron:neutron-extensions:neutron-jsr-120'
include 'neutron:neutron-extensions:neutron-jsr-135'
include 'neutron:neutron-extensions:neutron-jsr-75'
include 'neutron:neutron-extensions:neutron-jsr-82'
include 'neutron:neutron-extensions:neutron-nokiaui'
include 'neutron:neutron-extensions:neutron-siemensapi'
include 'neutron:neutron-extensions:neutron-site-skin'
include 'neutron:neutron-injected'

include 'neutron:neutron-javase'
include 'neutron:neutron-javase-applet'
include 'neutron:neutron-javase-swing'

include 'neutron:neutron-midp'
include 'neutron:neutron-tests'
include 'neutron:neutron-tests:bytecode-test-app'
include 'neutron:neutron-tests:neutron-test-avetana'
include 'neutron:neutron-tests:neutron-test-bluecove'

include 'neutron:neutron-webstart'
