-overloadaggressively
-defaultpackage 'me2'
-allowaccessmodification
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-keep public class * extends java.applet.Applet { *; }
-keep public class * implements org.neutron.microedition.io.ConnectionImplementation { *; }
-keep public class * implements org.neutron.cldc.ClosedConnection { *; }
-keep public class org.neutron.app.util.MIDletResourceLoader { public *; }
-keep public class org.neutron.app.util.MIDletThread { public *; }
-keep public class org.neutron.app.util.MIDletTimer { public *; }
-keep public class org.neutron.app.util.MIDletTimerTask { public *; }
-keep public class org.neutron.microedition.io.ConnectorImpl { *; }
-keep public class org.neutron.Injected { *; }
-keep public class org.neutron.device.** { public static <fields>; public <methods>; }
